### ISSUE TITLE
Test Echoes And Volumes Of Enemy SFX in relation to distance from Player Character

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#103]

**Comment by vitormaduro** [comment]
This is something that can already be done in Godot. Want me to implement a test scene to see how it looks?

**Comment by Pseudo-64** [comment]
> This is something that can already be done in Godot. Want me to implement a test scene to see how it looks?

Sure, go ahead and try with any stock audio like the godzilla or raptor audio from jurassic park.
