### ISSUE TITLE
Define how different melee attacks can be used

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#149]
Sugestion:
- Standing still: regular attack
- Walking: regular attack
- Running: regular attack, but faster/stronger (or maybe a pounce)
- Falling: diagonal swipe
- Jumping: swipe or pounce, depending on velocity

**Comment by Pseudo-64** [comment]
@vitormaduro So I have assigned different attack animations issues and sent their reference videos to mint in DMs. The current swipe attack animation that we've will be assigned to idle animation, that is, what you describe as Regular animation for standing still. 

The walking animation will recieve a new attack called upper-cut. 

The running animation will receive a new attack called "Both-claws swipe" (May need to workshop the name, but you'll get it when you see the attack"

The falling animation will receive a new attack called "Kitty-cat" attack. 

The jumping animation will receive the attack you have been asking for, "the Pounce attack".

**Comment by Pseudo-64** [comment]
@vitormaduro Since questions were answered and related animations were issued to mint, I am closing this issue. Let me know if its need reopening.
