### ISSUE TITLE
Temporary Icarasia Actor with AI

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#261]
Requirements:
- [ ] Implement the Icarasia Actor with temporary sprites. The AI is already defined, so it must work properly

**Comment by Pseudo-64** [comment]
@vitormaduro Bug Report. Am not able to pick up weapon without doing a melee first. It just growls over a weapon. 

https://drive.google.com/file/d/1b4In3YcJ4PznKPCca4rpNo7t64HcUBy1/view?usp=sharing
