### ISSUE TITLE
Icarasia's Detection Range

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#269]
Define how an Icarasia will act based on Hestmor's distance. No need to set any actual numbers for now, just an overview of what will happen when Hestmor is:
- Out of Range
- Far
- Close

**Comment by Pseudo-64** [comment]
@vitormaduro sorry for seeing this late, probably this is clear by now, from the mechanical workings you saw in https://github.com/Team-Awkward-Smile/Epilogue/wiki/Mechanical-Workings-Of-Individual-Enemies#icarsia. 
But still summarizing it here: 
* Out of Range: Icarasia moves left and right at its place, and/or searching for a Terra Bischem. If a Terra Bischem is there, they can be seen floating near it.
* Far: If Icarasia notices Hestmor from Far, then its height dependent. If Icarasia is higher or lower than Hestmor, then it will attempt a projectile attack. If its on the same plane or ground as Hestmor, it will attempt to get closer to her. If they are hit by Hestmor once, then they will approach her. 
* Close: Engage melee combat, aka, sting. 

If you feel the answer was to your satisfaction, feel free to close the issue, but if there are any dangling threads or confusion, feel free to say so.

**Comment by vitormaduro** [comment]
Honestly I don't remember why I opened this issue, but the entry on the wiki already answers this question, so I'm closing this issue hehehe
