### ISSUE TITLE
Test Ball Bouncing Simulations And Countering it back with Melee for Moss Plant of Guwama

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#291]
Currently don't mind it. We will discuss it after the testing of the Icarasia AI.

**Comment by vitormaduro** [comment]
@Pseudo-64 Do we still need this issue open? The Moss Plant was already merged

**Comment by Pseudo-64** [comment]
> @Pseudo-64 Do we still need this issue open? The Moss Plant was already merged

Yeah closing it now. Not needed anymore.
