### ISSUE TITLE
Make sample climbing sfx on rocky cave like grounds

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#322]
Similar cave like grounds as seen in the walking animation issues, just, this time, it's of our main character jumping and holding onto a ledge like this.

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/340fe494-8313-4fca-ac20-3469f38fc5cb)

And then climbing the ledge like this. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/fd37dbd6-9522-4356-95a7-1c326515e91a)

So I what i want from this sample sfx, is the subtle rock movement that happen when A) someone jumps and grabs a rocky ledge, and B) when some climbs that rocky ledge to the surface, and that subtle rock and leg scratching/other rock movements when that rocky ledge is climbed.

**Comment by davidebunino** [comment]
A) 
[Rock Grab Ledge.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13835173/Rock.Grab.Ledge.zip)
B)
[Rock Climb.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13835176/Rock.Climb.zip)
@Pseudo-64 @vitormaduro
