### ISSUE TITLE
Make sample of sliding sfx of rubble falling

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#323]
We have a sliding animation like this: 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/2dc7e48f-f62d-4bfa-833e-3fe57d40c9e7)

And at points the character may slide down a rubble of rocks that may look like this: 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/565a1971-b638-4d6f-9ca9-ec5c8839db05)

So, again, need the sfx for the rock rubbles that may fall when a character is sliding on them.

**Comment by davidebunino** [comment]
[Rock Slide.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13835178/Rock.Slide.zip)
@Pseudo-64 @vitormaduro
