### ISSUE TITLE
Make sample SFX of a gunshot followed by its echo

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#326]
What it means. Currently we are still planning how our guns will look, but for now, a sample of a gun being shot inside a cave. So the gun shot, followed by its echo. It could be any gun you want, just whatever type of gun you decide to choose -- shotgun, machine gun, pistol -- make sure to mark it, since we have some placeholders we need to check.

**Comment by vitormaduro** [comment]
The echo can be applied directly in Godot, and doing it that way allow us to play around with the settings to change the echo at runtime. The SFX can be created with echo built-in, but I think it will be harder for no good reason

**Comment by Pseudo-64** [comment]
@vitormaduro I am well aware, but i just want to test for standard reasons. If Davide gives us a echo audio, we can atleast mark a particular point in case to keep in mind for echoes so we would know what to play around with on the godot and where. 

Again, this is just test audio, and i am not using any test audio in the final game. All of this is just for audio standard testing.

**Comment by davidebunino** [comment]
[Gunshot.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13887729/Gunshot.zip)
wrong export, my bad. this is the correct version
(as I said in the previous comment are the only stereo sounds, so you can study the reverb better)
