### ISSUE TITLE
Make sample sfx of claws scratching against cave walls

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#327]
What I want to test is, what if the player does a melee near a wall. So we have a melee attack like this: 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/f6cef3a4-ff8c-49fe-9100-f7a18b5cf043)

There are other melee attacks, but for now, you can use this as reference, and their SFX against a rocky wall would most probably be the same, regardless of attack. 
Basically if the player melee nears a wall or on a rock, the claws should make some scratching noise, as if they are scratching against the rock's surface. 

If you make this, try to make sure not make it sound too screechy, as it can be hard to stand, but yeah, that scratch of a claw swiftly against a rocky surface should be there.

**Comment by Pseudo-64** [comment]
@vitormaduro tagging you as well, since this is something i had been meaning to test for a while, sound wise.

**Comment by davidebunino** [comment]
[Scratch Wall.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13887411/Scratch.Wall.zip)
@Pseudo-64 @vitormaduro

**Comment by vitormaduro** [comment]
@Pseudo-64 When will this SFX be used?

**Comment by Pseudo-64** [comment]
@vitormaduro read the description. Basically if the player does a melee near a wall that is unbreakable, it will play to indicate her claws are scratching against it.
