### ISSUE TITLE
make sample sfx of rock breaking apart/shattering

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#328]
So at points, the player will encounter rocks that they can break with melee or gun. 
Just sfx of them shattering to ground after being broken.

**Comment by davidebunino** [comment]
Just for info: Size of the rocks relative to the player?

**Comment by Pseudo-64** [comment]
@davidebunino sending you what i send you on DM 

> About the rock, i would say, the rocks size vary, but for testing purposes, you can think of the rock being 2 times the size of the player.

> The canonical height of the player character is 6ft. So you can think an 12 feet long rock shattering.

**Comment by davidebunino** [comment]
[Breaking Rock.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/13887787/Breaking.Rock.zip)
made very quickly, maybe they are a little too strong
@Pseudo-64 @vitormaduro

**Comment by davidebunino** [comment]
[RockBreaking2.0.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/15379608/RockBreaking2.0.zip)
Sounds update, I would alternate them to have more variety in the game, I don't know if you have a way to put a random pitch variations when the sound is triggered, but in that case please use a range from -1 to +1 semitones
Thanks!
@vitormaduro @Pseudo-64
