### ISSUE TITLE
Define Audio Export Guidelines

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#354]
Define a common parameter on the basis of the audio exports provided by the three sound people. 

1) Ryan 

> -2dB 32k is often what I do 👍

2) Rinkaku 

> so the LUFS i usually do around -14dB, it's a bit quieter than my normal songs

> i have a plugin to see how much LUFS a song has, and yes it's always a negative value unless there's something really wrong with the audio

3) Davide 

> I usually export in .wav 24 bit, 48 Khz (files not overly large but with very good quality)

> Regarding lufs it changes a lot from project to project and from gameplay requirements.
> If I had to say a very general standard would be the following: 
> o -15 UI sfx
> o -16/-18 general sfx 
> o -18/-20 music, ambience, background sfx
> 44.1/48 khz in my opinion is the sweet spot between files dimension and quality

4) Info provided by Vitor 

> The sound buses in Godot go from -6 dB (very loud) to 72 dB (almost no sound)

**Comment by Pseudo-64** [comment]
@vitormaduro needed some clarification on something. You said the sound buses in godot went from -6dB to 72 dB, was this in reference to the inbuilt sound editor provided by godot, or the lufs supported. Because the dB for all the davide and rinkaku sounds seems to be going below -6dB. Rinkaku in particular seems to be making their soundtracks in-14dB. 
I might be getting something wrong and confusing myself, so let me know.

**Comment by vitormaduro** [comment]
@Pseudo-64 Sorry, I'm dumb when it comes to audio and I read the UI wrong. When dragging the slider up and down, Godot actually shows the values, and it turns out the buses go from +6 dB to -80dB

![image](https://github.com/Team-Awkward-Smile/Epilogue/assets/49737868/80735736-9566-4edb-b7b4-f38c44476305)
