### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#37]
The final game must support controllers, and ideally they should be "hot-swappable", meaning that plugging a controller or starting to use it while the game is running should work immediately, while changing the action prompts to the correct sprites.

Requirements:
- [x] Define which controllers will be supported (DualShock, Xbox, Nintendo, etc.)
- [x] Define if custom sprites will be created for each button of each controller
- [x] Make sure every action is mapped by default to a controller input
- [x] Change the action sprites to their controller variants whenever an input is detected from a controller (and vice-versa)

**Comment by Pseudo-64** [comment]
@vitormaduro since all controller support tasks are done, I am closing this one, but feel free to re-open if needed.
