### ISSUE TITLE
Make SFX for Walking On Flesh Ground

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#396]
So imagine a ground made of meat. Particular like this one: 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/dfced8e4-edae-455d-936d-c41887f2a63d)

And the walking animation is the same as the previous one. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/8d738593-8336-4010-88db-fc82fe463c64)

**Comment by Mediocre-At-Best** [comment]
[FleshWalkSfx.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/15451970/FleshWalkSfx.zip)
@vitormaduro
