### ISSUE TITLE
Make SFX for Hestmor Getting Hurt/Dying

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#407]
The sprite animation is this: 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/cc3b0439-e954-40f5-8081-2654ece39114)

This SFX could be used for both Hestmor losing a life, and kicking the bucket. Maybe we may just keep this animation for death, and give just a slight bounce back to the sprite, but either way, this sfx could be needed in the sprite animation shown below. The two components that would make up this SFX would be her falling, and her letting out a light exhale of air. I could explain what I mean, but I time traveled back in time, and asked my good friend Christopher Lee to explain it. Take it away Christopher!

https://www.youtube.com/watch?v=adJdBSdMGKU

So yeah, that exhale of air, mixed with her Hitting the ground. Here's the animation.

**Comment by Mediocre-At-Best** [comment]
[Death Breaths for hestmor.zip](https://github.com/user-attachments/files/17196751/Death.Breaths.for.hestmor.zip)
@vitormaduro @Hhk187
