### ISSUE TITLE
Make SFX for Hestmor Breathing when Idle

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#413]
When, the player character is idle, she will stand there and take heavy breaths. We actually have a non-test sprite for it. Here it is. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/aa200630-fa34-4584-93f7-21329b71f64c)

**Comment by Mediocre-At-Best** [comment]
[HestmorIdleBreathingLoop.zip](https://github.com/user-attachments/files/16616319/HestmorIdleBreathingLoop.zip)
@vitormaduro @Hhk187

**Comment by Hhk187** [comment]
Ok, will make the change when i can

**Comment by Mediocre-At-Best** [comment]
[HestmorIdleBreathingLoop Fade In.zip](https://github.com/user-attachments/files/16757734/HestmorIdleBreathingLoop.Fade.In.zip)
Pretty sure you already updated it but just uploading here to have it here @Hhk187

**Comment by Pseudo-64** [comment]
@Hhk187 merger with develop approved on this one.
