### ISSUE TITLE
Make SFX for Hestmor Rolling In Flesh

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#419]
Again, a fleshy surface made completely of meat and flesh. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/5f1cd930-8133-4fc4-b096-8ab09a149a80)

So, we hear how her skin may squish against it. 

And also, here's the rolling animation. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/ffb56957-d7ef-4c5a-81ba-d71c946f3dc4)

**Comment by Mediocre-At-Best** [comment]
[HestmorFleshRoll.zip](https://github.com/user-attachments/files/15856461/HestmorFleshRoll.zip)
@vitormaduro

**Comment by Hhk187** [comment]
Feature done. Now Hestmor plays rolling sfx depending on the ground type (flesh or rock). Waiting for Vitormaduro approval :)

**Comment by Mediocre-At-Best** [comment]
[HestmorFleshRollQuieter.zip](https://github.com/user-attachments/files/16468715/HestmorFleshRollQuieter.zip)
@vitormaduro @Hhk187

**Comment by Pseudo-64** [comment]
@vitormaduro @Hhk187 if this was implemented, please close the issue.
