### ISSUE TITLE
Make SFX of Hestmor Crouching

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#420]
Basically to give sound to the movement of he player, when they crouches downwards. So that bending of the player's spine or body movement going on all four should be taken into account for. 

Here's how the crouching animation looks like: 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/346dd5e6-4d6c-4b0c-b731-54722f569d8c)

**Comment by Mediocre-At-Best** [comment]
[Hestmor_Crouch.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/15330851/Hestmor_Crouch.zip)
@vitormaduro

**Comment by Pseudo-64** [comment]
@vitormaduro currently moved this to testing, but will close it once its properly implemented volume-wise on branch 420.
