### ISSUE TITLE
Test sliding and sliding cancelling

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#44]
Read for more detail in the Physics section of the GDD, which I will port next week to the wiki. Basically whenever mint creates a sliding animation for BOB, then two states need to be check.
The player executing the slide, and the player canceling the slide midway to jump up (for now when said cancellation happens, just try to switch between the sliding sprite and the standing sprite. When we start work of Hestmor, we will try to see if cancelling the slide could have its own executable animation.)

**Comment by vitormaduro** [comment]
Released in #88
