### ISSUE TITLE
Create A Prototypical Glory State Animation For The Prototype Testing Enemy Sprite Called ROB

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#52]

**Comment by Pseudo-64** [comment]
@vitormaduro same, thing. was there a glory state animation for it.

**Comment by vitormaduro** [comment]
![Rob-stunn_copy](https://github.com/Team-Awkward-Smile/Epilogue/assets/49737868/94508505-4cf0-4f6f-a899-4e269594f3ab)

This one, with an orange blinking added by code (we can change the color later)

**Comment by Pseudo-64** [comment]
@vitormaduro okay, then closing both of them.
