### ISSUE TITLE
Loading Icon

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#524]
![image](https://github.com/Team-Awkward-Smile/Epilogue/assets/49737868/fc408b6f-a412-4dd0-95f0-62592c88a2d8)

@Pseudo-64 Please confirm, is the icon only to be used when auto-saving, or can we use it when the game is loading a level as well?

**Comment by Pseudo-64** [comment]
@vitormaduro @Hhk187 Yes, this is the autosave icon to be used.
