### ISSUE TITLE
Create A Prototypical Animation Of ROB being Ripped Apart Revealing A Gun Sprite Inside Him

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#53]

**Comment by Pseudo-64** [comment]
@vitormaduro haven't tested the rob branch in a while, but was there any animation of rob being ripped apart revealing a gun. I believe there was, but just double checking before closing the issue.

**Comment by vitormaduro** [comment]
![Rob-rip](https://github.com/Team-Awkward-Smile/Epilogue/assets/49737868/8e7d97eb-c938-40b9-b9c3-47d73fd70d66)

There's this one
