### ISSUE TITLE
Crawling and Squatting

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#572]
Two new movement options for Hestmor when the player holds down the `CrawlSquat` key:
- If Hestmor is unarmed, she will crawl (using the crouching animation) and be able to move around on all fours. Letting go of the key will make her stand up
   - This is the `Crawl` State
- If Hestmor is holding a gun, she will squat (using a new animation), reducing her Hurtbox and allowing her to shoot while standing still. She will not be able to move while in this State, and letting go of the key will make her stand up
   - This is the `Squat` State
 
Things to consider: 
- What's the difference between Crawling and the Long Slide? If both of them shrink Hestmor's size equally, then it's redundant to have two similar movement options
   - Suggestion: Crawling may reduce her size even further, or allow her to move up slopes. This will create a clear distinction between the two movement options
- Will Squatting offer any additional bonuses besides a reduced Hurtbox? When you crouch in a game, you usually get a bonus to aim and shoot at things that are father away
   - Suggestion: maybe reducing the recoil of the gun (decreasing how much the shots are spread while firing continuously), or slowing down the rate at which the spread increases (although there's no recoil/spread system in place for now) 

@Pseudo-64 @Hhk187 Suggestions and feedback are welcome

**Comment by Hhk187** [comment]
Maybe when Squatting, she could see farther as well?, what i mean is, when she squats, the camera goes to the left or right depending where she is looking.

for exemple

![image](https://github.com/user-attachments/assets/5ca86445-d8fe-4935-9aba-5d637fd6558a)
 
![image](https://github.com/user-attachments/assets/8967d05c-3fa9-4c26-a37e-d14d910b7d25)

**Comment by Pseudo-64** [comment]
@vitormaduro I like the suggestion made by @Hhk187.  Maybe the look button could be implemented similar to how crawling is implemented. Basically you holding down the squatting key and pressing left or right directional buttons to look farther left or farther right. 
Let us know your thoughts. 

(P.S. do not confuse directional buttons with aiming buttons, just saying for clarity)

**Comment by Pseudo-64** [comment]
@vitormaduro adding this here, so I get used to discussing branches in issues, but current changes that may be needed to the branch would be: 

- [ ] making gun dissolve in tight spaces 
- [ ] make turning during crawling possible
