### ISSUE TITLE
Create Test Sound Effect For Swiping Attack

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#63]
Here is the test sprite to help you out.

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/260f6e9a-a097-4c3f-ae9d-4f8e5dfd8c1d)

**Comment by RyanXMesscher** [comment]
[SwipingAttack_SFX.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/11887227/SwipingAttack_SFX.zip)

**Comment by vitormaduro** [comment]
Implemented in #41
