### ISSUE TITLE
Create Test Sound Effect For Glory Attack

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#64]
Here is the test sprite to help you out.

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/2685a3c8-8d20-4d0e-89a8-c57b86f72427)

**Comment by RyanXMesscher** [comment]
[GloryAttack_SFX.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/11887234/GloryAttack_SFX.zip)

**Comment by vitormaduro** [comment]
Implemented in #68
