### ISSUE TITLE
Create Test Sound Effect For Walking On Flesh

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#65]
Imagine a ground made of complete flesh, and then a six foot tall creature walking on it barefoot.

All I can provide for now is the walking sprite of the creature. 

![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/75238e15-5bf9-4d3a-a951-a0506f522a6f)

**Comment by RyanXMesscher** [comment]
[WalkingOnFlesh_SFX_Loop.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/11887240/WalkingOnFlesh_SFX_Loop.zip)
