### ISSUE TITLE
Create Test Sound Effect For Jumping

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#66]
![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/6f98f2cb-4481-4e64-9eb6-d0028a1f5a10)

**Comment by RyanXMesscher** [comment]
[Jumping_SFX.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/11887223/Jumping_SFX.zip)

**Comment by vitormaduro** [comment]
Implemented in #41
