### ISSUE TITLE
Create Test Sound Effect For Sliding

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Awkward-Smile/Epilogue#67]
![Image](https://github.com/Team-Awkward-Smile/Epilogue/assets/92845232/272c9571-931c-4164-b933-f81b4209befe)

**Comment by RyanXMesscher** [comment]
[Slide_SFX.zip](https://github.com/Team-Awkward-Smile/Epilogue/files/11887244/Slide_SFX.zip)

**Comment by vitormaduro** [comment]
Implemented in #41
