### ISSUE TITLE
Bob rotates when standing too close of a ledge

### ISSUE THREAD

**Issue by vitormaduro** [Team-Awkward-Smile/Epilogue#83]
Because of the Capsule Collider used for Bob, when standing too close of a ledge, the game will mistake the angled terrain for a slope and rotate Bob to match the rotation of the "slope". This causes Bob to rotate weirdly when you walk off ground.

Requirements:
- [x] Bob must remain straight while walking off ground, but rotate to match the angle of a slope

**Comment by Pseudo-64** [comment]
@vitormaduro since this was fixed, am closing the issue.
